### ISSUE TITLE
how to create router link?

### ISSUE THREAD

**Issue by umefarooq** [nativescript-vue/nativescript-vue-navigator#1]
How to create router link with this package, same way vue router link are created or other way?

**Comment by rigor789** [comment]
There is no `<router-link>` instead you need to call `$navigator.navigate(to, options)`.

For example
```xml
<Button text="Navigate" @tap="$navigator.navigate('/some/other/route', { clearHistory: true })" />
```

Or if called from the component's methods
```js
export default {
  methods: {
    doStuff() {
      this.$navigator.navigate('/some/route', { backstackVisible: false })
    }
  }
}
```
