### ISSUE TITLE
value.resolvedPage.__path always undefined

### ISSUE THREAD

**Issue by ScottAtRedHawk** [nativescript-vue/nativescript-vue-navigator#13]
Hi,
In [/components/Navigator.js line 46](https://github.com/nativescript-vue/nativescript-vue-navigator/blob/9b7a87cbb5f771e84120ab1943ce21fbe96518d0/components/Navigator.js#L46) value.resolvedPage.__path is always undefined, so the call to [_updatePath()](https://github.com/nativescript-vue/nativescript-vue-navigator/blob/9b7a87cbb5f771e84120ab1943ce21fbe96518d0/index.js#L38-L40) always passes the default route. The routing is working as far as screens go, but when I call this.$navigator.route in a component, it is always the default route object and not the current route that the app has navigated to.

**Comment by rigor789** [comment]
@ScottAtRedHawk can you include a sample repository where this is not working? I'm using this pacakage with nativescript 6.x and it's working (`this.$navigator.route` works too).

**Comment by ScottAtRedHawk** [comment]
I'm not sure what I'm doing but it seems to work intermittently. I'm going to close this because I don't think it's an issue with the package, but rather my code. Thanks!

**Comment by rigor789** [comment]
@ScottAtRedHawk if you need help debugging, share your  issue on Slack, someone might be able to spot the issue!
