### ISSUE TITLE
Doesn't work on created()

### ISSUE THREAD

**Issue by jdinartejesus** [nativescript-vue/nativescript-vue-navigator#14]
I'm trying to redirect to a confirm-email page after login on the dashboard but doesn't work as expected. Currently navigates to confirm-email page but after returns to dashboard.

Eg.
```
// dashboard.vue
...
created () {
   this.$navigator.navigate('/confirm-email', { clearHistory: true })
}
```
Currently: Login -> Dashboard -> Confirm-Email -> Dashboard
Expected: Login -> Dashboard -> Confirm-Email 

Thanks!

**Comment by rigor789** [comment]
Unfortunately navigation can only happen when Frame/Pages are loaded - try using the `loaded` event and triggering a navigation from there.

**Comment by jdinartejesus** [comment]
Thanks @rigor789
