### ISSUE TITLE
Changing UIViewControllerBasedStatusBarAppearance breaks UIBarStyle

### ISSUE THREAD

**Issue by darrenkhouston** [nativescript-vue/nativescript-vue-navigator#16]
When setting the info.plist `UIViewControllerBasedStatusBarAppearance` to `true` and the `UIStatusBarStyle` set to `UIStatusBarStyleLightContent`, I have no control over the statusbar text color, only the background. If I stop using this plugin and go back to the regular Manual Router, this problem is solved.

Seems to be related to this issue, but this is all I could find about it.

[[iOS] Multiple frame breaks UIBarStyle #6771](https://github.com/NativeScript/NativeScript/issues/6771)

**Comment by rigor789** [comment]
Could not reproduce it working with the Manual router either, as it seems `barStyle` has been deprecated? 

I managed to get it working fine with
```js
UIApplication.sharedApplication.setStatusBarStyleAnimated(0, true)
// or 
UIApplication.sharedApplication.setStatusBarStyleAnimated(1, true)
```

**Comment by darrenkhouston** [comment]
> Could not reproduce it working with the Manual router either, as it seems `barStyle` has been deprecated?
> 
> I managed to get it working fine with
> 
> ```js
> UIApplication.sharedApplication.setStatusBarStyleAnimated(0, true)
> // or 
> UIApplication.sharedApplication.setStatusBarStyleAnimated(1, true)
> ```

Yep. This fixed the issue for me. Thanks @rigor789
