### ISSUE TITLE
App not rendering

### ISSUE THREAD

**Issue by patrikengborg** [nativescript-vue/nativescript-vue-navigator#2]
Hi,

I would really like this to work, but I'm just getting a blank empty app now. When inspecting in Dev tools I can se that the `<Frame>` is empty.

Is the current release supposed to be in a functional state? Maybe it's possible to include a more complete example, including one of the page components?

Thanks.

**Comment by rigor789** [comment]
There was a refactor which broke the default route resolution, just pushed out a fix for that.
