### ISSUE TITLE
Navigator loses Frame reference when displaying multiple Frames on IOS

### ISSUE THREAD

**Issue by Lehren** [nativescript-vue/nativescript-vue-navigator#24]
The navigator will break navigation on IOS when a new Frame instance is created somewhere. For instance when showing a modal that is structured like so:

```
<Frame>
    <Page>
        <Label> Hello </Label>
    </Page>
</Frame
```

And then closing the modal, all navigation stops, at least on IOS. My guess is due to the fact the navigator cannot find the 'default' Frame anymore, or it is using the frame of the closed and discarded modal. Resulting in errors.

**Comment by Lehren** [comment]
The fix seems to be to set the id and ref of the modal `Frame` to something other than 'default'. Might be useful to put into the docs or something. Or for any future visitors :)

**Comment by rigor789** [comment]
Tracked at https://github.com/nativescript-vue/nativescript-vue-navigator/issues/27
