### ISSUE TITLE
Meta Info Bug. Not Updating

### ISSUE THREAD

**Issue by juanbonoso** [nativescript-vue/nativescript-vue-navigator#30]
Hi,

First, thanks for this awesome plugin , i really like it.

I just realized that meta info, is not being update when i pass from one page to another with 
`this.$navigator.navigate();`

I use the loaded page event from nativescript to verify if the user have autorization to open a particular page: 

```
public loadPage() {
		this.store.auth.isLoggedIn().then(isLoggedIn => {
			if (!isLoggedIn) {
				console.log(this.$navigator.route.meta.needsAuth);
				console.log(JSON.stringify(this.$navigator.route.meta));
				if (this.$navigator.route.meta.needsAuth) {
					// this.$navigator.navigate('/OnBoard', { clearHistory: true });
				}
			}
		});
```
The console.log will always show:  
**true
'{"needsAuth":true,"name":"AdminInterface"}'**

AdminInterface is the page, where loadPage is triggered. I also have the same loadPage in OnBoard where triggers the same output from AdminInterface all the time, which makes my app to enter in infinite Loop, navigating every second to OnBoard.

routes file: 

```
'/OnBoard': {
		component: OnBoard,
		meta: {
			needsAuth: false,
			name: 'OnBoard',
		},
		props: {
			userType: '',
		},
	},
'/AdminInterface': {
		component: AdminInterface,
		meta: {
			needsAuth: true,
			name: 'AdminInterface',
		},
		props: {
			userType: '',
		},
	}

```

**Comment by rigor789** [comment]
I suspect the meta is not yet showing the new route's meta in the `@loaded` event. Can you try adding a slight delay with `setTimeout` just to confirm the case?

**Comment by juanbonoso** [comment]
@rigor789 I just tried it with a setTimeOut of 10 seconds (10000 miliseconds), and did not work.  So it is not the loaded event.

**Comment by superalex** [comment]
@juanbonoso are you using using style Vue components?

**Comment by juanbonoso** [comment]
@superalex I am using vue class components.

**Comment by superalex** [comment]
So I think we have the same issue: https://github.com/nativescript-vue/nativescript-vue-navigator/issues/31

**Comment by juanbonoso** [comment]
Yes, I just read just issue and we have the same problem.

**Comment by rigor789** [comment]
Let's consolidate this into #31
