### ISSUE TITLE
dynamic routes support

### ISSUE THREAD

**Issue by kabaluyot** [nativescript-vue/nativescript-vue-navigator#35]

**Comment by rigor789** [comment]
What do you mean by dynamic routes? What would they solve that's not already possible?

**Comment by kabaluyot** [comment]
Like in vue router, we can provide and create a dynamic route by passing it in params:

e.g

/social:id or /social/{id}

and passing id lets say 24415 will give us:

/social/24415

**Comment by rigor789** [comment]
Navigator is intentionally simple - you can achieve the same thing by passing in the id as a prop.

```js
this.$navigator.navigate(`/categories', { props: { id: 1234 } })
```

**Comment by kabaluyot** [comment]
Hmm, I think I made myself confused. The question should be intended to generate a dynamic page and the navigator can just pass it like your example. Thank for your time and sorry :)

**Comment by mreall** [comment]
Dynamic routes would be particularly helpful for apps that consume a web API.  My Vue web app can receive a dynamic route from the API and route to a page that processes the parameters from the URL.  Any component on the rendered page can then read the URL to access the parameters.

With Navigator, when I get a URL from the API, I have to convert it to a Navigator path with props, then pass the props from parent component to child component.  This makes it harder to share nativescript components with the web app and more complicated to share the URL parameters.
