### ISSUE TITLE
VueX store is unavailable on new pages

### ISSUE THREAD

**Issue by mtancoigne** [nativescript-vue/nativescript-vue-navigator#5]
Hi !

I use VueX to manage the app's state. It works fine on the `defaultPage` but I can't navigate to views that uses it:

```js
// Works on defaultPage
computed: {
  isAuth(){ return this.$store.getters.isAuth }
}
// This error shows up when trying to navigate to a page that does the same:
//   [Vue warn]: Error in render: "TypeError: Cannot read property 'getters' of undefined"
// and the pages does not renders.
```

The whole `$store` object is not available to new views; I guess it also may be the same for other objects/plugins

---

* **navigator version:** 0.0.3
* **nativescript:** 5
* **nativescript-vue:** 2.0.2
* **VueX:** 3.0.1

**Comment by jeremy-saidani** [comment]
Hi,

Same problem for me, did you find a solution ?

**Comment by mtancoigne** [comment]
Absolutely not; I continue to use a messy workaround to handle routes.

**Comment by jeremy-saidani** [comment]
Do you use this._vm.$navigateTo() in actions ? If I use this, the store will be undefined in next page
But if a use this.$navigateTo() in component, it works great

**Comment by mtancoigne** [comment]
I used `this.$navigateTo()`

**Comment by wpatter6** [comment]
It seems like what is actually happening is that child components of the navigated to component are not getting the store, but the parent is.  Another work around is to bubble events up to the parent and have that access the store.  Obviously not ideal, but possibly this info helps solve the bug...

**Comment by jawa-the-hutt** [comment]
You can work around this issue with a local copy of the plugin as you'll have to edit it directly.

You'll have to replace `this.$navigateTo(matchedRoute.component, options)` with `topmost().currentPage.__vuePageRef__.$navigateTo(matchedRoute.component, options)` here: https://github.com/nativescript-vue/nativescript-vue-navigator/blob/1109e11141ffa55e80797ca20564f322e2c5249f/index.js#L52

And replace `this.$navigateBack.call(this, args)` with `topmost().currentPage.__vuePageRef__.$navigateBack.call(this, args)` here: https://github.com/nativescript-vue/nativescript-vue-navigator/blob/1109e11141ffa55e80797ca20564f322e2c5249f/index.js#L55

That being said....I have no idea of this is a good workaround or now.  I've put a question out to @rigor789 to see if this is something that should be done or not.

**Comment by jawa-the-hutt** [comment]
fyi, here's a repo that reproduces the issue:  https://github.com/jawa-the-hutt/ns-vue-navigator-test

it does NOT include the workaround in my previous comment.

**Comment by errozero** [comment]
I have the same problem, it happens to the main component that was navigated to. I have an app with 2 screens, one uses the store, if I navigate away and come back, the store is no longer available.

I worked around it by importing the store into each component that requires it instead of injecting it into the Vue instance.

**Comment by rigor789** [comment]
Generally the issues is most likely due to the "weird" parent/child relations between navigated components (I have plans to improve this, but it wasn't straight-forward when I last worked on it). Does setting `Vue.prototype.$store = store` in your main file solve the issues? (I've been recommending this for a while now, as this should prevent issues like these - but looking at the docs now it's not mentioned anywhere 🤔 )

**Comment by wpatter6** [comment]
Setting the prototype seems to have fixed it for me

**Comment by KinsleySen** [comment]
> Generally the issues is most likely due to the "weird" parent/child relations between navigated components (I have plans to improve this, but it wasn't straight-forward when I last worked on it). Does setting `Vue.prototype.$store = store` in your main file solve the issues? (I've been recommending this for a while now, as this should prevent issues like these - but looking at the docs now it's not mentioned anywhere thinking )

works like a charm

**Comment by mivd7** [comment]
I'm getting the same issue. App works fine in xcode emulator but not on my iphone when running tns preview. Tried to set` Vue.prototype.$store = store` in main.js, as recommended above, but still getting this error: 

> CONSOLE ERROR file:///app/tns_modules/nativescript-vue/dist/index.js:2129:20: [Vue warn]: Error in render: "TypeError: this.$store.getters is not an Object. (evaluating 'val in this.$store.getters')"
> 
> found in
> 
> ---> <App> at App.vue
>        <Frame>
>          <Root>
> LOG from device iPhone van MI: CONSOLE ERROR file:///app/tns_modules/nativescript-vue/dist/index.js:2129:20: [Vue warn]: Error in nextTick: "TypeError: this.$store.getters is not an Object. (evaluating 'val in this.$store.getters')"

please help, I really want to show my app to someone on their phone and not just on the emulator on my own mac.
