### ISSUE TITLE
Compatibility with RadSideDrawer in a NS-Vue app?

### ISSUE THREAD

**Issue by michaelsmedley** [nativescript-vue/nativescript-vue-navigator#66]
Hi

I have an app that is using the RadSideDrawer component to open up a sidebar on button click.  I am struggling to get this to work with the setup I have.

My App.vue template currently looks like this:

```
<template lang="html">
<RadSideDrawer
    ref="drawer"
    drawerLocation="Left"
    gesturesEnabled="true"
    :drawerTransition="transition"
  >
    <StackLayout ~drawerContent backgroundColor="#ffffff">
      <slot name="drawerContent" />
    </StackLayout>
    <Frame ~mainContent ref="drawerMainContent">
      <slot name="mainContent" />
    </Frame>
  </RadSideDrawer>
  
</template>
```

So my initial instinct was to replace the <Frame> tag with the <Navigator> tag, however this just loads a blank screen for me.  If I move the above RadSideDrawer logic into a page (such as ./components/HomePage.vue) then the app crashes instantly for me.

Any help will be much appreciated

**Comment by rigor789** [comment]
If you are using the navigator - replace
```html
<Frame ~mainContent ref="drawerMainContent">
  <slot name="mainContent" />
</Frame>
```

with 

```html
<Navigator ~mainContent  />
```

But that may not be all - share more of the project if still having issues. (This is easier to answer on Slack/Discord rather than an issue)

**Comment by michaelsmedley** [comment]
@rigor789 Hey, I really appreciate the response.

That simple line you sent me seems to have done the trick, at least for the few different frames I have tried!

Many thanks again - you have spared me several more hours looking into it!!
