### ISSUE TITLE
Cant access added meta on page

### ISSUE THREAD

**Issue by MohammedBashiru** [nativescript-vue/nativescript-vue-navigator#7]
`export const routes =  {
	'/login': {
    	component: Login
  	},
  	'/tm-root': {
    	component: Root,
    	meta: { needsAuth: true, page_title: "Home" }
  	},
  	'/tour-manager-home': {
	    component: TourManagerHome,
	    meta: { needsAuth: true, page_title: "Home" }
	},

}`

But when I tried to get a computed property of the page name is resulted in 

> TypeError: Cannot read property 'meta' of undefined

console.log("page_title", this.$navigator.route.meta.page_title)

**Comment by Jonarod** [comment]
I had the same problem myself. I guess you are calling `this.$navigator.route.meta.page_title` OUTSIDE of the `<Navigator />` component (like in your root app for example).

I was able to acces it this way:

```
($navigator.route && $navigator.route.meta && $navigator.route.meta.page_title)
```

**Comment by dantanie** [comment]
Hi @Jonarod Thanks for the reply.
Yes I need to call it outside the `<Navigator />` because I need to display the page title on the parent component.

I have not tried this yet because am away from computer. Can you please confirm this will work outside the `<Navigator />` component. ?

`($navigator.route && $navigator.route.meta && $navigator.route.meta.page_title)`

Thanks

**Comment by Jonarod** [comment]
Well it works outside the Navigator component for me :)

**Comment by dantanie** [comment]
Ok thanks @Jonarod I will try it again when I get back to the project.

**Comment by dantanie** [comment]
Thanks @Jonarod It worked.

**Comment by Jonarod** [comment]
I just found out the hack does NOT work on iOS...

**Comment by dantanie** [comment]
> I just found out the hack does NOT work on iOS...

That sucks. Thanks for letting me know

**Comment by Jonarod** [comment]
Hey @dantanie I was able to get current page name on iOS using:

```
this.$navigator.path
``` 
hope it helps

**Comment by dantanie** [comment]
Wow, thanks. I really appreciate the support.

Regards.

*Mohammed Bashiru*
*Multi-Platform Software Engineer*

*Mobile: +233 546 891 427*

*Email: mohammedbashiru63@gmail.com <mohammedbashiru63@gmail.com>*

*Website: https:iammohammedb.com <mohammedbashiru63@gmail.com>*

Code-In Ghana

                   https://iammohammedb.com/register


KS-Ltd
Key Beverage Distributor in Ghana

FOODS-INN[image: Logo (2)]

                    Ghana Limited

SIMU-DRIVE

                    Ghana Limited
